export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",    
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS",  
    
    FETCH_CART : "FETCH_CART",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART"
};